[tasks.build_web]
dependencies = ["bundle"]

[tasks.bundle]
script_runner = "@shell"
script = ["npx rollup ./index.js --format iife --file ./bundle.js"]
dependencies = ["copy_to_root"]

[tasks.copy_to_root]
script_runner = "@shell"
script = '''
cp ./pkg/serde_web_converter_bg.wasm ./
cp ./pkg/serde_web_converter.js ./
'''
dependencies = ["wasm_pack_build"]

[tasks.wasm_pack_build]
command = "wasm-pack"
args = ["build", "--target", "web"]

[tasks.copy_files_to_export]
script_runner = "@shell"
script = '''
mkdir export
mkdir export/pkg
cp ./index.html export
cp ./index.css export
cp ./pkg/bundle.js export/pkg
cp ./pkg/serde_web_converter_bg.wasm export/pkg
cp ./pkg/serde_web_converter.js export/pkg
'''