[tasks.build_web]
dependencies = ["bundle"]

[tasks.bundle]
script_runner = "@shell"
script = ["npx rollup ./index.js --format iife --file ./bundle.js"]
dependencies = ["wasm_pack_build"]

[tasks.wasm_pack_build]
command = "wasm-pack"
args = ["build", "--target", "web"]

[tasks.prepare_export]
script_runner = "@shell"
script = '''
rm -rf export
mkdir export
ln index.html export/index.html
ln index.css export/index.css
ln bundle.js export/bundle.js
ln pkg/serde_web_converter_bg.wasm export/serde_web_converter_bg.wasm
ln FiraCode-Regular.ttf export/FiraCode-Regular.ttf
'''
dependencies = ["bundle"]